// Diamond
export const DIAMOND_OVERLAY = "DIAMOND_OVERLAY";
export const DIAMOND_SHINE = "DIAMOND_SHINE";
export const DIAMOND_SUNSHINE = "DIAMOND_SUNSHINE";
export const EXPLOSION_PARTICLE = "EXPLOSION_PARTICLE";
export const ONE_PARTICLE = "ONE_PARTICLE";
export const SYMBOL_DIAMOND = "SYMBOL_DIAMOND";
export const WHITE_PARTICLE = "WHITE_PARTICLE";